-- CreateTable
CREATE TABLE `themes` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT false,
    `primaryColor` VARCHAR(191) NOT NULL,
    `primaryHex` VARCHAR(191) NOT NULL,
    `secondaryColor` VARCHAR(191) NOT NULL,
    `secondaryHex` VARCHAR(191) NOT NULL,
    `accentColor` VARCHAR(191) NOT NULL,
    `accentHex` VARCHAR(191) NOT NULL,
    `headerBg` VARCHAR(191) NOT NULL,
    `headerBgHex` VARCHAR(191) NOT NULL,
    `headerText` VARCHAR(191) NOT NULL,
    `headerTextHex` VARCHAR(191) NOT NULL,
    `sidebarBg` VARCHAR(191) NOT NULL,
    `sidebarBgHex` VARCHAR(191) NOT NULL,
    `sidebarText` VARCHAR(191) NOT NULL,
    `sidebarTextHex` VARCHAR(191) NOT NULL,
    `sidebarActive` VARCHAR(191) NOT NULL,
    `sidebarActiveHex` VARCHAR(191) NOT NULL,
    `bodyBg` VARCHAR(191) NOT NULL,
    `bodyBgHex` VARCHAR(191) NOT NULL,
    `bodyText` VARCHAR(191) NOT NULL,
    `bodyTextHex` VARCHAR(191) NOT NULL,
    `cardBg` VARCHAR(191) NOT NULL,
    `cardBgHex` VARCHAR(191) NOT NULL,
    `cardBorder` VARCHAR(191) NOT NULL,
    `cardBorderHex` VARCHAR(191) NOT NULL,
    `buttonPrimary` VARCHAR(191) NOT NULL,
    `buttonPrimaryHex` VARCHAR(191) NOT NULL,
    `buttonSecondary` VARCHAR(191) NOT NULL,
    `buttonSecondaryHex` VARCHAR(191) NOT NULL,
    `footerBg` VARCHAR(191) NOT NULL,
    `footerBgHex` VARCHAR(191) NOT NULL,
    `footerText` VARCHAR(191) NOT NULL,
    `footerTextHex` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `themes_name_key`(`name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
